name: before-gra
main: com.gmail.noxdawn.Plugin
version: 0.1-ALPHA
author: Fulva
commands:
  echofuck:
    description: A test command
  setsuperdrop:
    description: let your drop item fly
  removesuperdrop:
    description: let your drop item no longer fly
  issuperdrop:
    description: let you know if you have superdrop
  setnofallarrow:
    description: let arrow not fall
  removenofallarrow:
    description: let arrow fall
  isnofallarrow:
    description: let you know if your arrow fall
  creeper:
    description: the target player will suffer from attack of a creeper
    usage: /creeper <player-name>
  uncreeper:
    description: cancel the effect of the creeper command
    usage: /uncreeper <player-name>
  playcreeper:
    description: make creeper sound behide a player
    usage: /playcreeper <player-name>
  playcreeperattach:
    description: creeper sound behide a player continuesly
    usage: /playcreeperattach [player-name]
  playcreeperdettach:
    description: stop creeper sound behide a player continuesly
    usage: /playcreeperdettach [player-name]
  contiarrowitem:
    description: make the item in your hand a super arrow launcher
    usage: /contiarrowitem

api-version: '1.15'
